language: ruby
rvm:
  - 2.3.1
before_install:
  - nvm install 6.2.0
install:
  - bundle install --jobs=3 --retry=3
  - npm install
before_script:
  - bundle exec rake db:test:prepare
script:
  - bundle exec rake health
cache:
  bundler: true
  directories:
  - node_modules
addons:
  code_climate:
    repo_token: 14c18d2f4d345c1846a7f8ec1d2bcbf161d78fe10a2713bcd922b3d66ade10eb
